# Generated by Django 4.2 on 2025-04-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('mobile', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='about_cat',
            field=models.TextField(max_length=2000),
        ),
    ]
