# Generated by Django 4.2 on 2025-04-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='product_img',
            new_name='item_img',
        ),
    ]
