# Generated by Django 4.2 on 2025-04-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_product_img_item_item_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
