# Generated by Django 4.2 on 2025-04-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
