# Generated by Django 4.2 on 2025-04-06 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_product_wishlist_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.AddField(
            model_name='cart',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='Item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
