# Generated by Django 4.2 on 2025-04-06 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_cart_product_remove_wishlist_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Item',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'item')},
        ),
    ]
